on:
  release:
    types:
      - created

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

# Thanks: https://rakhim.exotext.com/how-to-build-and-publish-multi-platform-rust-binaries
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build the executable
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Tar x86_64 binary
        run: tar -czvf toxo-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release toxo

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 toxo-gnu-linux-x86_64.tar.gz > toxo-gnu-linux-x86_64.tar.gz.sha256

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["toxo-gnu-linux-x86_64.tar.gz", "toxo-gnu-linux-x86_64.tar.gz.sha256"]'
  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install rustup targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build the executable
        run: cargo build --release --target=x86_64-apple-darwin --target=aarch64-apple-darwin

      - name: Zip x86_64 binary
        run: tar -czvf toxo-macos-x86_64.tar.gz -C target/x86_64-apple-darwin/release toxo

      - name: Zip arm64 binary
        run: tar -czvf toxo-macos-aarch64.tar.gz -C target/aarch64-apple-darwin/release toxo

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 toxo-macos-x86_64.tar.gz > toxo-macos-x86_64.tar.gz.sha256
          shasum -a 256 toxo-macos-aarch64.tar.gz > toxo-macos-aarch64.tar.gz.sha256

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["toxo-macos-x86_64.tar.gz", "toxo-macos-aarch64.tar.gz", "toxo-macos-x86_64.tar.gz.sha256", "toxo-macos-aarch64.tar.gz.sha256"]'
